### ISSUE TITLE
Source map comment not being added to the output of file

### ISSUE THREAD

**Issue by jorbs** [csstools/postcss-sass#39]
Hi,

I am trying to add the source map URL to my compiled CSS, but the comment line (`sourceMappingURL=...`) doesn't appear in the output file. I am using the following PostCSS config below:
```
module.exports = {
  plugins: [
    require('autoprefixer'),
    require('postcss-preset-env')({stage: 4}),
    require('@csstools/postcss-sass')({
      includePaths: ['./node_modules'],
      quietDeps: true,
      omitSourceMapUrl: true,
    }),
  ],
};
```

I've also tried `sourceMapUrls` sass-dart option (https://sass-lang.com/documentation/cli/dart-sass/#source-map-urls), but it doesn't work.

How can I do that?

**Comment by romainmenke** [comment]
I think you need to use the PostCSS API's to configure sourcemaps.

`@csstools/postcss-sass` doesn't drive the output CSS or the output sourcemaps.
It only parsed Sass inputs and converts these to plain CSS so that PostCSS can process it.

see : https://postcss.org/api/#sourcemapoptions

You should check the documentation of your PostCSS runner, but maybe this will work :

```js
module.exports = {
  map: {
    inline: true,
  },
  plugins: [
    require('autoprefixer'),
    require('postcss-preset-env')({stage: 4}),
    require('@csstools/postcss-sass')({
      includePaths: ['./node_modules'],
      quietDeps: true,
      omitSourceMapUrl: true,
    }),
  ],
};
```

**Comment by romainmenke** [comment]
I've added a test to confirm that this works and to guard against regressions : https://github.com/csstools/postcss-sass/commit/313816e8e9526d7cee3c3660298d89dc6510c298#diff-040b0eebb600e7c5c7c81149ab7c9fcea37746fc200692627eff732c58f1ef00R61-R69
