### ISSUE TITLE
Dart-Sass isn't receiving options set in plugin

### ISSUE THREAD

**Issue by frankyonnetti** [csstools/postcss-sass#41]
It appears that `dart-sass` is not receiving options set in the plugin for `postcss-sass`. In this example, I am passing the ['compressed' style option](https://sass-lang.com/documentation/js-api/interfaces/options/#style), but the output remains expanded.

```JavaScript
// postcss.config.js
...

  plugins: [
    require('autoprefixer')(),
    require('@csstools/postcss-sass')({
      style: 'compressed' // not working
    })

...
```

Setup a simple test case
https://github.com/frankyonnetti/postcss-sass-options

Thanks!

**Comment by rxnlabs** [comment]
@frankyonnetti I was running into a similar issue where passing options to `dart-sass` via this postcss-sass plugin was not working. I looked at the source code and it looks like this plugin is in fact passing the options to `dart-sass` but the options but the options are not passed in the correct format that dart-sass expects. This plugin is calling sass https://github.com/csstools/postcss-sass/blob/main/dist/index.cjs#L176 `render` function https://sass-lang.com/documentation/js-api/functions/render/ and the render function expects these options https://sass-lang.com/documentation/js-api/interfaces/legacyfileoptions/ . These are the supported options that the `render` function uses.

So for your use case to use the compressed style, you would pass the option `outputStyle` instead of `style`

```js
// postcss.config.js
plugins: [
    require('autoprefixer')(),
    require('@csstools/postcss-sass')({
      outputStyle: 'compressed' // this works
    })
```

For my case, I wanted to use dart-sass's `--quiet` option to silence warnings about future deprecated features like the slash-div deprecation https://sass-lang.com/documentation/cli/dart-sass/#quiet but the option was not working. I had to create a Logger object to do this https://sass-lang.com/documentation/js-api/interfaces/legacyfileoptions/#logger, which was more complicated than it's worth. I decided I could live with the warnings and fix the code rather than introducing uneeded complexity into the `postcss.config.js` file.

**Comment by frankyonnetti** [comment]
Hey @rxnlabs thank you! I didn't even think to use legacy options.
